apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: vietnam
  name: vietnam-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: vietnam
  type: NodePort
status:
  loadBalancer: {}
