# Simple Kubernetes Pod to deploy the app contained in nigelpoulton/getting-started-k8s:1.0
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: vietnam
spec:
  containers:
    - name: web-ctr
      image: kienbt/vietnam:v0.1
      ports:
        - containerPort: 8080
